spring:
  config:
    import: optional:file:./../.env[.properties] # read environment variables from .env file
  application:
    name: poy-wallet-dev
  main:
    banner-mode: console
  banner:
    location: classpath:/banner.txt
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use Grunt + BrowserSync for livereload
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  flyway:
    enabled: true
    placeholderReplacement: false
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: debug