spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_USERNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org.springframework.security: debug